# NumPy

NumPy es la principal biblioteca de la computación científica en python. El corazón de NumPy es la clase ndarray con esta podemos realizar diferentes tipos de operaciones matemáticas como:
* Algebra Lineal Basica
* Operaciones Lógicas
* Ordenamiento
* Operaciones estadísticas básicas
* Transformaciones discretas de Fourier

## Arreglo 
Es una colección de elementos de un mismo tipo de dato. La dimensión de un arreglo es la cantidad de indices necesarias para acceder a un elemento del arreglo.

![](../img/img_00.jpg)

## ndarray

Para la creación de un arreglo en NumPy, se utiliza la clase **ndarray**.



In [0]:
# Importamos NumPy
import numpy as np # Por convención se usa el pseudonimo np

# Recibe como parametro una lista
arreglo = np.array([[1, 2],
                    [3, 4]])

lista = [[3, 4],[5, 6]]

arreglo_lista = np.array(lista)

print(arreglo)

[[1 2]
 [3 4]]


## Atributos ndarray

Los atributos más importantes del ndarray son los siguientes.

| Atributo | Descripción                                                    |
|----------|----------------------------------------------------------------|
| ndim     | Número de dimensiones del arreglo                              |
| size     | Número total de elementos del arreglo.                         |
| shape    | Tupla de la cantidad de elementos de cada dimensión.           |
| dtype    | Tipo de dato de los elementos arreglo(Tipos propios de numpy). |

In [0]:
arreglo_1 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]) 

print("Número de dimensiones del arreglo: {}".format(arreglo_1.ndim))
print("Número total de elementos del arreglo: {}".format(arreglo_1.size))
print("Cantidad de elementos de cada dimensión: {}".format(arreglo_1.shape))
print("Tipo de dato de los elementos arreglo: {}".format(arreglo_1.dtype))

Número de dimensiones del arreglo: 2
Número total de elementos del arreglo: 9
Cantidad de elementos de cada dimensión: (3, 3)
Tipo de dato de los elementos arreglo: int64


## Escalares

In [0]:
x = np.array(6)
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


## Vectores

In [0]:
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype) 

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


### Funciones utiles para crear Vectores

* `arange()`: es una función util para crear un vector. Recibe el inicio, el fin, del vector y el incremento en cada elemento y crea un vector con elementos dados por el intervalo y que se distribuyan de acuerdo al incremento
* `linspace()`: es una función util para crear un vector. Recibe el inicio, el fin del vector y el tamaño del mismo y crea un vector con elementos segmentados uniformemente

In [0]:
# arange

vector_cero_al_ocho = np.arange(9)  # Crea un vector que posee los enteros del cero al ocho
print("Vector de 0 a 8: {} ".format(vector_cero_al_ocho))

vector_dos_al_nueve = np.arange(2, 10)  # Crea un vector que posee los enteros del 2 al 9
print("Vector de 2 a 9: {} ".format(vector_dos_al_nueve))

vector_uno_al_doce_de_tres_en_tres = np.arange(1, 14, 3)  # Crea un vector que posee los enteros del 1 al 13 con incrementos de 3
print("Vector de 1 a 12 con incrementos de 3: {} ".format(vector_uno_al_doce_de_tres_en_tres))

Vector de 0 a 8: [0 1 2 3 4 5 6 7 8] 
Vector de 2 a 9: [2 3 4 5 6 7 8 9] 
Vector de 1 a 12 con incrementos de 3: [ 1  4  7 10 13] 


In [0]:
# linspace

vector_de_cero_a_ocho = np.linspace(0, 8)  
print("Vector de linspace de 0 a 8 sin especificar cantidad de elementos: \n{}".format(vector_de_cero_a_ocho))

vector_de_cero_a_ocho = np.linspace(1, 10, 9)  
print("Vector de 9 elementos segmentados uniformemente entre 1 y 10 : {}".format(vector_de_cero_a_ocho))

Vector de linspace de 0 a 8 sin especificar cantidad de elementos: 
[0.         0.16326531 0.32653061 0.48979592 0.65306122 0.81632653
 0.97959184 1.14285714 1.30612245 1.46938776 1.63265306 1.79591837
 1.95918367 2.12244898 2.28571429 2.44897959 2.6122449  2.7755102
 2.93877551 3.10204082 3.26530612 3.42857143 3.59183673 3.75510204
 3.91836735 4.08163265 4.24489796 4.40816327 4.57142857 4.73469388
 4.89795918 5.06122449 5.2244898  5.3877551  5.55102041 5.71428571
 5.87755102 6.04081633 6.20408163 6.36734694 6.53061224 6.69387755
 6.85714286 7.02040816 7.18367347 7.34693878 7.51020408 7.67346939
 7.83673469 8.        ]
Vector de 9 elementos segmentados uniformemente entre 1 y 10 : [ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


### Indexación

Para acceder a los elementos de un arreglo utilizamos indices o un arreglo de elementos de tipo logico. Recordemos que los indices de un arreglo en programación, empiezan en el número 0.

Para acceder a los elementos de un arreglo mediante indices simplemente escribimos dentro de los corchetes el indice al que queremos acceder, en caso de acceder a un intervalo debemos indicarllo de la forma `v[a:b]` donde el intervalo es de la forma `[a,b)` es decir accedemos a los elementos cuyos indices van de (a) a (b-1)

Se incluyen ejemplos de ambas formas en la parte de abajo

![](../img/img_01.png)

In [0]:
v = np.arange(2, 10)
print("Todo el vector:", v)   # Muestra todo el vector
print("Todo el vector:", v[:])  # Muestra todo el vector
print("Primer elemento:", v[0])  # Muestra el primer elmento
print("Ultimo Elemento:", v[-1])  # Ultimo elemento
print("Excepto el ultimo elemento:", v[:-1])  # Excepto el último
print("Excepto el primero:", v[1:])  # Excepto el primero
print("Del segundo al antepenultimo:", v[2:-2])  # Del segundo al antepenultimo
print("Del segundo al antepenultimo de dos en dos:", v[2:-2:2])  # Del segundo al antepenultimo de dos en dos
print("Orden inverso", v[::-1])  # Orden inverso
print("Del antepenultimo al segundo en orden inverso:", v[-2:2:-1])

Todo el vector: [2 3 4 5 6 7 8 9]
Todo el vector: [2 3 4 5 6 7 8 9]
Primer elemento: 2
Ultimo Elemento: 9
Excepto el ultimo elemento: [2 3 4 5 6 7 8]
Excepto el primero: [3 4 5 6 7 8 9]
Del segundo al antepenultimo: [4 5 6 7]
Del segundo al antepenultimo de dos en dos: [4 6]
Orden inverso [9 8 7 6 5 4 3 2]
Del antepenultimo al segundo en orden inverso: [8 7 6 5]


In [0]:
v = np.arange(3, 10)
print("Vector Original:", v)

indices_a_los_que_queremos_acceder = np.array([1,3,4])
print("Vector resultante de acceder por indices contenidos en un vector:", v[indices_a_los_que_queremos_acceder])

vector_booleano = v % 2 == 0
print("Vector Booleano:", vector_booleano)
print("Valores accedidos por el vector booleano:", v[vector_booleano])

Vector Original: [3 4 5 6 7 8 9]
Vector resultante de acceder por indices contenidos en un vector: [4 6 7]
Vector Booleano: [False  True False  True False  True False]
Valores accedidos por el vector booleano: [4 6 8]


### Funciones Importantes hhhhhhhhh

Las funciones más comunes que se realizan con vectores son las siguientes hhhhh

In [0]:
v = np.array([1, -2, 3, -4, -2]) # Creamos un vector

print("El elemento menor del vector es:", v.min())
print("El elemento mayor del vector es:", v.max())
print("La desviación estandar del vector es:", v.std())
print("La suma de todos los elementos del vector es:", v.sum())
print("El vector ordenado es:", np.sort(v))
print("Indice del elemento mayor:", np.argmax(v))
print("Indice del elemento menor:", np.argmin(v))

# Concatenar vectores

El elemento menor del vector es: -4
El elemento mayor del vector es: 3
La desviación estandar del vector es: 2.4819347291981715
La suma de todos los elementos del vector es: -4
El vector ordenado es: [-4 -2 -2  1  3]
Indice del elemento mayor: 2
Indice del elemento menor: 3


### Operaciones con Vectores

Estas son las operaciones más comunes que se pueden hacer con vectores

In [0]:
c = 10
x=np.array([1,1,1])
y = np.array([2,4,5])
print("suma x+y=", x+y)
print("producto uno a uno", x*y)
print("producto punto", x@y)
print("producto escalar", x*c)

suma x+y= [3 5 6]
producto uno a uno [2 4 5]
producto punto 11
producto escalar [10 10 10]


## Matriz

In [0]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
x ndim:  2
x shape: (3, 3)
x size:  9
x dtype:  int64


## Funciones para crear Matrices

Las funciones para crear matrices son:
* `np.eye(n)`: permite crear la matriz identidad de orden n

In [0]:
matriz_identidad = np.eye(10)  # Matriz identidad de orden 10
print("Matriz Identidad:\n", matriz_identidad)

Matriz Identidad:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## Indexación

Para acceder a elementos de una matriz se realiza de forma similar que con vector, es decir, los indices dentro de corchetes. La matriz al ser de dimension dos (dos ejes) se requieren dos indices para acceder a un elemento de la misma. Los indices empiezan en 0.

In [0]:
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print("Toda la matriz:\n", m)  # Accedemos a todos los elementos
print("Toda la matriz:\n", m[:])  # Accedemos a todos los elementos
print("Accediendo a los elementos del renglon 1:", m[1])  # Accediendo a los elementos del renglon 1
print("Accediendo a toda la matriz:\n", m[:, :])
print("Accediendo a toda la matriz:\n", m[:, ])
print("Accediendo al elemento '6':", m[1, 2])
print("Accediendo al elemento '6':", m[1][2])
print("Accediendo a los elementos de la columna tres:", m[:, 2])
print("Accediendo a los elementos de la columna tres y dos  y asociados al renglon 1", m[2, 1:])

col = [0, 2]
ren = [0, 1]
print("Accediendo a los elementos con renglones", ren, "y columnas", col, "respectivamente:", m[ren, col])

ren = [True, True, False]
col = [True, False, True]
print("Accediendo a los elementos con renglones", ren, "y columnas", col, "respectivamente:", m[ren, col])

Toda la matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Toda la matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Accediendo a los elementos del renglon 1: [4 5 6]
Accediendo a toda la matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Accediendo a toda la matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Accediendo al elemento '6': 6
Accediendo al elemento '6': 6
Accediendo a los elementos de la columna tres: [3 6 9]
Accediendo a los elementos de la columna tres y dos  y asociados al renglon 1 [8 9]
Accediendo a los elementos con renglones [0, 1] y columnas [0, 2] respectivamente: [1 6]
Accediendo a los elementos con renglones [True, True, False] y columnas [True, False, True] respectivamente: [1 6]


In [0]:
# Accediendo mediante una matriz booleana

m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
m_pares = m % 2 == 0
print("matriz booleana:\n", m_pares)
print("elementos pares:\n", m[m_pares])

matriz booleana:
 [[False  True False]
 [ True False  True]
 [False  True False]]
elementos pares:
 [2 4 6 8]


### Ejes

Los axis(ejes) de un arreglo de numpy son la orientación de los indices en el arreglo

![](../img/img_05.png)

#### Operaciones sobre ejes

Numpy nos facilita el trabajo cuando estamos operando matrices. Ofrece funciones que se pueden aplicar sobre un eje o sobre toda la matriz. Algunos ejemplos:

In [0]:
# En la mayoría de las funciones podemos especificar a que eje (dimension) lo aplicaremos
# Funcion argmax
m = np.array([[3,2,4],
              [1,5,6],
              [7,8,9]])

print("Toda la matriz:\n", m)
print("Mayor de toda la matriz:", m.max())
print("Mayor en cada columna:", m.max(axis=0))
print("Mayor en cada renglon:", m.max(axis=1))

print("Matriz Ordenada por cada Renglon:\n", np.sort(m))
print("Covarianza de la matriz:\n", np.cov(m))

# Las siguientes funciones también se pueden realizar por axis
print("El elemento menor de la matriz es:", m.min())
print("La desviación estandar de la matriz es:", m.std())
print("La suma de todos los elementos de la matriz es:", m.sum())
print("Posición del elemento mayor:", np.argmax(m))
print("Posición del elemento menor:", np.argmin(m))

Toda la matriz:
 [[3 2 4]
 [1 5 6]
 [7 8 9]]
Mayor de toda la matriz: 9
Mayor en cada columna: [7 8 9]
Mayor en cada renglon: [4 6 9]
Matriz Ordenada por cada Renglon:
 [[2 3 4]
 [1 5 6]
 [7 8 9]]
Covarianza de la matriz:
 [[1.  0.5 0.5]
 [0.5 7.  2.5]
 [0.5 2.5 1. ]]
El elemento menor de la matriz es: 1
La desviación estandar de la matriz es: 2.581988897471611
La suma de todos los elementos de la matriz es: 45
Posición del elemento mayor: 8
Posición del elemento menor: 3


### Opearciones con Matrices

#### Suma y Resta de matrices

Numpy realiza la suma y resta usual de matrices

#### Multplicación y Division de matrices

Para realizar mutliplicacón de arreglos se utiliza el producto de Hadamard o mutliplicación element-wise(Elemento por elemento)

![](../img/img_03.png)

![](../img/img_02.png)

Y la divsion de Hadamard se denota así:

![](../img/img_04.png)

In [0]:
c = 4+5j
y = np.eye(3)
print("suma matricial\n", x+y)
print("producto hadamart\n", x*y)
print("producto matricial\n", x@y)
print("producto escalar\n", x*c)
x = np.array([[1,2,3], [4,5,6]])
print("Transpuesta de x\n", x.T)

suma matricial
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
producto hadamart
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
producto matricial
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
producto escalar
 [[ 4. +5.j  8.+10.j 12.+15.j]
 [16.+20.j 20.+25.j 24.+30.j]
 [28.+35.j 32.+40.j 36.+45.j]]
Transpuesta de x
 [[1 4]
 [2 5]
 [3 6]]


### Funciones Relacionadas con Algebra Lineal

In [0]:
m = np.array([[1, 2],
             [3, 4]])
m2 = np.array([[1,2,3],
              [4,5,6]])

print("Transpuesta:\n", m.T)
print("Inversa:\n", np.linalg.inv(m))
print("Pseudo inversa:\n", np.linalg.pinv(m))

#print("Inversa:\n", np.linalg.inv(m2))
print("Pseudo inversa:\n", np.linalg.pinv(m2))

#Determinante
print("Determinante:", np.linalg.det(m))

# De matriz a vector
print("Vector a partir de m: ", m.flatten())  # 'F'

Transpuesta:
 [[1 3]
 [2 4]]
Inversa:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Pseudo inversa:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Pseudo inversa:
 [[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]
Determinante: -2.0000000000000004
Vector a partir de m:  [1 2 3 4]


#### Resolver un Sistema de Ecuaciones

Sea el sistema de ecuaciones:
$$2x_1+3x_2=11$$
$$3x_1+5x_2=21$$

In [0]:
m = np.array([[2, 3],
              [3, 5]])
y = np.array([11, 21])
print("Usando multiplicación de matrices:\n", np.linalg.inv(m) @ y)
print("Usando función de numpy:\n", np.linalg.solve(m, y))

Usando multiplicación de matrices:
 [-8.  9.]
Usando función de numpy:
 [-8.  9.]


## Tensor

In [0]:
t = np.array([
              [[1,2],
               [3,4]],

              [[5,6],
               [7,8]]
             ])
print ("t:\n", t)
print ("t ndim: ", t.ndim)
print ("t shape:", t.shape)
print ("t size: ", t.size)
print ("t dtype: ", t.dtype) 

t:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
t ndim:  3
t shape: (2, 2, 2)
t size:  8
t dtype:  int64


### Funciones utiles para crear ndarrays

Existen funciones para crear ndarray en base a su shape algunas de ellas son:

* `np.ones(shape)`: Permite crear un arreglo llenado con puros unos
* `np.zeros(shape)`: Permite crear un arreglo llenado con puros ceros
* `np.empty(shape)`: Permite crear un arreglo con valores no inicializados
* `np.random.random(shape)`: Permite crear un arreglo con valores entre cero y uno
* `np.title(arreglo, shape)`: Repite un arreglo en la forma shape
* `np.repeate(a, repeats, axis=None)`: Permite repetir un arreglo

In [0]:
vector_nulo = np.zeros([4])
print("Vector nulo:", vector_nulo)

matriz_unos = np.ones([3,4])
print("Matriz \n", matriz_unos)

# Creacion de un arreglo el cual sus elementos son cero
arreglo_aleatorio = np.random.random([2,3,4])
print("Arreglo de ceros:\n", arreglo_aleatorio)

# Cracion de una matriz sin entradas inicializadas, NumPy les asigna valores aleatorios
arreglo_vacio = np.empty([2, 3])
print("Arreglo vacio:\n", arreglo_vacio)

a = np.array([0, 1, 2])
print("Original:", a, "Title:",  np.tile(a, 2))

Vector nulo: [0. 0. 0. 0.]
Matriz 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arreglo de ceros:
 [[[0.42906137 0.60041123 0.33671289 0.0187256 ]
  [0.41835088 0.19022087 0.46757129 0.34988487]
  [0.50633661 0.10009727 0.79311908 0.08960143]]

 [[0.37029602 0.83559134 0.23254862 0.44136534]
  [0.58739622 0.38811138 0.43882275 0.51460944]
  [0.7358574  0.65620095 0.49460281 0.55522903]]]
Arreglo vacio:
 [[0.e+000 5.e-324 1.e-323]
 [0.e+000 5.e-324 1.e-323]]
Original: [0 1 2] Title: [0 1 2 0 1 2]


## Modificando el Shape de un ndarray

El atributo shape de un ndarray dice cuantos elementos hay en cada eje del arreglo y la longitud de shape nos dice la dimensión. Podemos modificar el atributo shape de un ndarray con las funciones:

* `resize(shape)`: Modifica el shape de un arreglo modificando el shape del arreglo 
* `reshape(shape)`: Modifica el shape de un arreglo creando un nuevo arreglo

**El producto de todos los elementos del nuevo shape debe ser igual al producto de todos los elementos del antiguo shape**

In [0]:
m = np.arange(10)
print(m.shape)

m.resize([2, 5])
print("usando resize", m.shape)
a=m.reshape([1,10])
# usamos reshape


print("usando reshape", m.shape)
print(a.shape)

(10,)
usando resize (2, 5)
usando reshape (2, 5)
(1, 10)


# Uniendo ndarrays

Para unir ndarrays usamos principalemente las funciones:

* `np.vstack(lista_de_ndarrays)`: Une arreglos de forma vertical
* `np.hstack(lista_de_ndarrays)`: Une arreglos de forma horizontal

In [0]:
m1 = np.arange(9).reshape([3, 3])
m2 = np.arange(9, 18).reshape([3, 3])

print("Union vertical:\n", np.vstack([m1, m2]))
print("Union horizontal:\n", np.hstack([m1, m2]))

Union vertical:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
Union horizontal:
 [[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


## BroadCasting

BroadCasting es la posibilidad de que un arreglo de que un arreglo posea la misma shape que otro arreglo para hacer una determinada operacion, estas operaciones son `+, -, *, /, **, %, //`

Para que puedan hacer BroadCasting se deben cumplir que cada elemento del arreglo de izquierda a derecha cumpla con alguna de las siguientes reglas estas son:
1. Ambos elementos son el mismo
2. Un elemento vale uno

Si no se cumple con alguna de estas reglas no se puede aplicar broadcasting

Por ejemplo, poseemos un arreglo con los elementos a1 `[1,2]` cuya shape es `(2)`y otro arreglo a2 con los elementos   
`[[1,1],  
  [1,1],  
  [1,1]]` cuya shape es `(3, 2)`
 
Entonces vemos si cumplen con las reglas:  
Primer elemento de derecha a izquierda: el primer elemento del primer arreglo es 2 y del segundo arreglo es 2 por lo que cumplen con la primera regla, asi que analizamos los siguentes elementos
Segundo elemento de dercha a izquierda: El segundo elemento del primer arreglo es 1 (siempre se ponen unos cuando no hay elemento) y del segundo arreglo es 3 por lo que cumplen la segunda regla asi que pasamos a los siguientes elementos
Tercer elemenento de derecha a izquierda: No hay mas elementos por lo que se puede aplicar BroadCasting

Para hacer la operación lo que hara es convertir la shape de a1 a `(3, 2)` y la shape de a2 la mantendra hara eso para poder efectuar las operaciones. Y al convertir la shape de a1 duplicara sus elementos hasta conseguir determinada shape

In [0]:
arreglo1 = np.array([1,2])
arreglo2 = np.array([[1,1],  
                     [1,1],  
                     [1,1]])
print("Suma:\n", arreglo1 + arreglo2)
print("Multiplicación:\n", arreglo1 * arreglo2)
print("División:\n", arreglo1 / arreglo2)
print("División Entera:\n", arreglo1 // arreglo2)
print("Exponencial:\n", arreglo1 ** arreglo2)
print("Modulo:\n", arreglo1 % arreglo2)

Suma:
 [[2 3]
 [2 3]
 [2 3]]
Multiplicación:
 [[1 2]
 [1 2]
 [1 2]]
División:
 [[1. 2.]
 [1. 2.]
 [1. 2.]]
División Entera:
 [[1 2]
 [1 2]
 [1 2]]
Exponencial:
 [[1 2]
 [1 2]
 [1 2]]
Modulo:
 [[0 0]
 [0 0]
 [0 0]]
